/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/Common/BaseModal.vue')['default']
    ButtonIcon: typeof import('./src/components/Atoms/ButtonIcon.vue')['default']
    CustomIcon: typeof import('./src/components/Atoms/CustomIcon.vue')['default']
    DropDown: typeof import('./src/components/Atoms/DropDown.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GuideItem: typeof import('./src/components/Guide/GuideItem.vue')['default']
    InputValidation: typeof import('./src/components/Atoms/InputValidation.vue')['default']
    ModalAdvancedSearch: typeof import('./src/components/Common/ModalAdvancedSearch.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar.vue')['default']
    PreviewItem: typeof import('./src/components/Common/PreviewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Common/SearchBar.vue')['default']
    SideBar: typeof import('./src/components/Layout/SideBar.vue')['default']
    ToolTip: typeof import('./src/components/Common/ToolTip.vue')['default']
    ToolTipBold: typeof import('./src/components/Common/ToolTipBold.vue')['default']
  }
}
