/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonIcon: typeof import('./src/components/Atoms/ButtonIcon.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GuideItem: typeof import('./src/components/Guide/GuideItem.vue')['default']
    InputValidation: typeof import('./src/components/Atoms/InputValidation.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Common/SearchBar.vue')['default']
    SideBar: typeof import('./src/components/Layout/SideBar.vue')['default']
    ToolTip: typeof import('./src/components/Common/ToolTip.vue')['default']
    ToolTipBold: typeof import('./src/components/Common/ToolTipBold.vue')['default']
  }
}
